### ISSUE TITLE
Declared Task can not be deleted or altered

### ISSUE THREAD

**Issue by SoarerBM** [weglide/bugtracker#109]
Declared Task can not be deleted after expiration.

Create New Task
Declare it for one day
Remove decleration or wait one day.
Not possible to change or delete task

Expected behavior:
A declared task, which is never flown, should be possible to delete.

**Comment by samuel-git** [comment]
It is a bit more complex.
What happens when the task is declared by someone else and you delete it? The declaration from the other person would need to be nullified. This would cause trouble.

You got an old version of the site. We added a delete for declared tasks which hide them from lists.
Please clear your cache to enable the update. Thanks

**Comment by SoarerBM** [comment]
Thanks for the information. Now i can delete(hide) the task.
