### ISSUE TITLE
Airport with multiple frequencies

### ISSUE THREAD

**Issue by Scumi** [weglide/bugtracker#133]
**Describe the bug**
We in EDBQ have multiple frequencies assigned, which are correctly stored in OpenAIP. 
The main frequency we use (INFO) is however not displayed in WeGlide. I also didn't find a way in OpenAIP to mark one frequency as "main" one.

**To Reproduce**
1. Go to https://weglide.org/airport/152159
2. Check frequency.

**Expected behavior**
Should be INFO - 133.330 MHz

**Screenshots**
n/a

**Device (please complete the following information):**
 - all

**Comment by samuel-git** [comment]
#138 with the same issue.

@moldhouse maybe provide and show all frequencies via API until we have a "main" marker?

**Comment by deltafox44** [comment]
Same problem with multiple runways. 

It seems that only the first runway (by QFU number) is displayed on the map and in airport info page. See for instance [Soria](https://www.weglide.org/airport/189927) which longest runway is 09/27 (correctly identified as "Main" in OpenAIP") but only shorter 02/20 492 m long is shown.

Also, the link [[Report false information](https://www.openaip.net/node/189927)](https://www.openaip.net/node/189927) is broken - it seems that it is since OpenAIP migrated to v2 last April. I don't know if WeGlide still use OpenAIP v1 data but, if so, all data will be obsolete soon...

**Comment by deltafox44** [comment]
Edit : the link to report false information to OpenAIP 2.0 is now working - thanks

the airport frequency problem seems to have been solved too...

I opened https://github.com/weglide/bugtracker/issues/214 for the runway problem remaining (only for the airport symbol on the map)

**Comment by deltafox44** [comment]
seems ok now both for frequencies and runways
