### ISSUE TITLE
New features appear only after emptying browser cache

### ISSUE THREAD

**Issue by niggli** [weglide/bugtracker#135]
**Describe the bug**
In safari, I tried to check out the new custom filters. The button never showed up, even after restarting, logging out and in again, and reloading the page. In Chrome everything worked. In Safari I had to empty the cache in the developer menu to make this new feature appear.

**To Reproduce**
see above

**Expected behavior**
I expect new features to show up without using developer features of the browser.

**Device (please complete the following information):**
 - Device: Macbook Pro
 - OS: MacOS Big Sur
 - Browser: Safari 14.0.3

**Comment by niggli** [comment]
Addition: behaviour is the same in Microsoft Edge 90.

**Comment by samuel-git** [comment]
Yes, this is a constant issue with some browsers and caching even when the request headers tell them not to. Usually it takes a couple of days to show the new features. We try to keep everything backwards compatible.

**Comment by samuel-git** [comment]
Should be better now but we do not have full control over browser behaviour. 

This is due to:
1. The browser needs to know there is a knew version and preparing the update
2. all tabs closed to prevent data inconsistency between tabs with different versions
3. Open again and new update should be present. No need to clear cache

The flow should happen at least sometimes for users (browser/system restart or new session).

The alternatives are less pretty (annoying update promt or data inconsistency).

Please re-open if the problem persists.
