### ISSUE TITLE
Livetracking Filter (Whitelist/Followed Pilots)

### ISSUE THREAD

**Issue by cpizer** [weglide/bugtracker#160]
When having a look at the livetracking feature on "busy" days,. it might be handy, if one could filter for specific gliders or pilots respectively.
A nice default filter might be one, that only includes pilotes one follows and which thereby are of high interest.
The filter might work in a way, that only the selected pilots are shown on the map and in the ranking.

**Comment by samuel-git** [comment]
Hey cpizer.
You can do that already. Just type in your search queries in the search box. You can combine as many queries as you want.
However, they are not reflected in the URL. We will add this for easy bookmarking in the future.
Thanks for the feedback!

**Comment by deltafox44** [comment]
Hi Samuel,
I understand that one can filter livetracking by pilot name(s), but is it possible to see "my friends" tracks (like in [ my friends flights](https://www.weglide.org/feed)) ?

**Comment by samuel-git** [comment]
Currently not. I was thinking about an additional "friends" filter and/or an extended friends feed with results from live tracking, segments from friends etc. What do you think, what are your ideas?

**Comment by deltafox44** [comment]
that would be fine - the best would be a button « only Friends » ON/OFF on the Live page, but a « friends » filter would be ok too

by the way, it is possible in Live to filter by full glider registration (i.e. D-KIDF), but not by contest number (i.e. DF) which would be more convenient

**Comment by cpizer** [comment]
A friends-filter or on/off button would be perfect in my opinion. Maybe a global "friends-only" option or switch would be an approach too, which applies while having a look at all rankings, tasks, flights, etc. This switch could be placed prominently and serve as an option to provide a "Social-Network-Feeling" on Weglide if required, which can be disabled within seconds.

**Comment by samuel-git** [comment]
Would be awesome for some but i fear that:
1. There is not enough space on small screens for an extra toggle
2. Very few People are actually logged in and have more than 5 friends (maybe 10%)
3. Global state changes of the "App" are difficult to understand for non technical people and hard to visualise in a comprehensive way

Just my 3 cents. Maybe we start with filters so the power users like you are happy. The filter system is alredy in place. Will think about a coherent way to include friends more everywhere.

Maybe we can prefere friends on the maps by displaying bigger aircrafts, checkmarks or other markings to distinguish them in lists and maps.

**Comment by deltafox44** [comment]
1 - A handy filter is entering departure airport(s) in the search box. Unfortunately, it doesn't work (still) by regions for live flights, the same way it works for past flights (see for instance [Bretagne](https://www.weglide.org/flight/map?order_by=-scoring_date&region=Bretagne,FR-BRE))

2 - It seems not all flights are shown on Weglide live, why ? See for instance what I see at the same moment (4 may 13:40 UTC) on Weglide (only 4 gliders) and Glideandseek (9 gliders)
![image](https://user-images.githubusercontent.com/82087770/166693340-4ea8b04e-8b43-4134-b6c5-87bab175572b.png)
![image](https://user-images.githubusercontent.com/82087770/166693457-bbe82525-ae7c-4193-b82d-cc9372564ef9.png)

3 - The gliders list shows only 5 or 6 gliders with 3 lines each, unless ones scrolls it down. Could it be possible to toggle between this sight and a more condensed sight ? For instance 1 line by glider, with only Contest number, Distance flown, Time flown, Altitude - MSL rather than AGL which is more significant IMHO) 

4 - the gliders list seems to be sorted by distance flown. Could it be possible to sort alternatively by MSL altitude, Contest number, Airport, etc...?

5 - Clicking on glider icon(s) or name(s) moves them on top of the list and shows their track(s) and their current altitude(s). Could it be possible to show also their barogram(s) below the map ? Currently this is only possible by clicking on Display for each glider one by one. It would be great to compare several barograms at once.

6 - Satellite pictures - this is a great feature ! Currently, when selecting one glider it is possible to synchronize the time of the satellite picture and the position of the glider. On the general Live view, it is possible to select the time of the satellite picture, but the position of the gliders remain the same (live positions). It would be great if it was possible to see the positions corresponding to the time of the satellite pictures (and/or a replay of all gliders for any time of the day, with or without satellite pictures)

That's all for the moment... Congratulations for the amazing features already there ;-)

**Comment by samuel-git** [comment]
Thank you for the excellent feedback!

1. Seems to work for me, can you describe what you would expect? When I select Bretagne it shows only flights which took off there. Do you mean that the URL can not be shared as the the filter is not reflected in the URL?

2. We currently have a bug with LX devices which is beeing fixed. Another cause could be that you [need to explicitely opt in](https://docs.weglide.org/livetracking/intro.html#opt-in) into tracking which is more privacy friendly.

3. Good point, we need to set a sensible default. A good middle way could be to reduce the info by one row but show all rows when the flight is selected.

4. Could be done, but I am not sure how as we only show the top 75 or so gliders of the current map viewport (user device performance reasons) and then "top" would be arbitrary. I would skip this for now.

5. This sounds like a good case for [multiflight view](https://www.weglide.org/flight/147607,147595,147510) of all the selected live flights. Another improvement would be right/left arrows next to the pilots name in live detail view for quick navigation between selected live flights.

6. We might have something to show here in the future ;-)

Stay tuned

**Comment by deltafox44** [comment]
1. Yes. It works for me with Hesse or other german regions, but not in France, even "Provence-Alpes-Côte-d’Azur
" were there is always many gliders in flight...

**Comment by samuel-git** [comment]
FR region filters will be added soon, lot's of new live functionality and bugfixes coming with next release (Friends filter, etc). Live Multiflight is noted but no ETA.
