### ISSUE TITLE
Back button missing

### ISSUE THREAD

**Issue by thbaero** [weglide/bugtracker#162]
**Describe the bug**
I'm viewing weglide on my iPad opening it directly from a saved bookmark on my Homescreen. Therefore I don't habe a browser bar with back and forward buttons for the webpage. 

Now, when I search for flights, get the list of results and open a specific flight I can't go back to the results list. There is no button that brings me back. 

**To Reproduce**
1. Use your iOS device
2. Open Safari and in there weglide 
3. Safe the webpage to the Homescreen
4. Open weglide directly from the Homescreen
5. Search for some flights
6. Open one of the flights from the result list
7. Try to go back to the results list (I can't find a suitable user interface for that action)

**Expected behavior**
I would expect to have some sort of back button to return to the result list. 

**Screenshots**

The yellow UI (next / previous flight) is ok. 
But I'm missing a "back to the list view button" (marked the missing UI in red). 

![image](https://user-images.githubusercontent.com/15811184/163727126-ec79a490-9b43-45ed-8887-91bae13e338a.jpeg)

**Device (please complete the following information):**
 - Device: iPad
 - OS: iOS current version
 - Browser: safari

**Comment by samuel-git** [comment]
Does the swiping from the left border to the center work like on other iOS devices?

On another note, I thought about a breeadcrumb navigation where the read marks are to act like a back button and give context because the navigation patterns on WeGlide grow quite complex.

PS: The bug where the barogram does not resize properly on iPads should be fixed for the next release.

**Comment by thbaero** [comment]
True. That works. Didn't think of this way until you mentioned it. Thanks for the tip.

**Comment by thbaero** [comment]
Btw, I love the breadcrumb idea...
