### ISSUE TITLE
Wrong aircraft type after uploading igc

### ISSUE THREAD

**Issue by tomascern** [weglide/bugtracker#177]
**Describe the bug**
Hi, I am using your API to upload IGC logs. Every time after upload I see in the log on the webpage incorrect aircraft type. I tried to use various gliders, but every time I see Duo Discus. It happened also when uploading directly in your webpage. 

**To Reproduce**
1. Upload IGC log via API or webpage
2. Login to your account
3. Open uploaded log detail
4. Check aircraft type

**Expected behavior**
Correct aircraft type is set in log detail.

**Example IGC**
[Lufty-08_38 13.05.22.igc.zip](https://github.com/weglide/bugtracker/files/8698837/Lufty-08_38.13.05.22.igc.zip)

**Comment by flyingjoe** [comment]
WeGlide remembers logger ids and will only guess the glider from `HFGTYGLIDERTYPE` once, when the logger has not been seen yet. When a logger is already known, we'll always set the last used glider.

This works 95% of the time since most loggers stay in the gliders.
Lufty doesn't seem to write use a distinct logger id but only calls itself `AXLF001`.
In comparison a Flarm writes `AFLAIF6`, `IF6` being the ID

**Comment by tomascern** [comment]
Ok, so what´s the sense of having aircraft_id parameter in /v1/igcfile API call?

**Comment by flyingjoe** [comment]
Ah, I thought you were just changing the aircraft in the IGC-file - Could you post a sample of the requests you are posting?

**Comment by tomascern** [comment]
I am using Alamofire iOS SDK, the transcript of the request is: 
```
curl https://api.weglide.org/v1/igcfile 
    -X POST 
    -H 'Authorization: Bearer xxx' 
    -H 'Content-Type: multipart/form-data; boundary=alamofire.boundary.50ba7c6f73a26434' 
    -d 'aircarft_id=549'
```

**Comment by flyingjoe** [comment]
Maybe it's the typo in aircraft_id?

**Comment by tomascern** [comment]
OMG, I feel embarrassed - that's it, now it works. Thank you for your help and I apologize for wasting your time.

**Comment by flyingjoe** [comment]
No worries, happens to all of us :)
