### ISSUE TITLE
Flights get uploaded without permission

### ISSUE THREAD

**Issue by flyingmarshel** [weglide/bugtracker#185]
While uploading a flight you need to check a box that you didn´t crossed any borders of airspaces etc. But even without checking the box and/or clicking the "Save-Button" the flight gets uploaded. 

**To Reproduce**
1. Upload an .igc file
2. Leave everything untouched (Checkbox and save-button)
3. Open a new tab and go to your profile
4. The flight will show up

**Expected behavior**
The flight will show up, even without the permission of the pilot. 

Device:
 - Desktop-PC and Android-device
 - OS: Windows 10 & Android 12
 - Browser: Firefox & Samsung Internet

**Comment by samuel-git** [comment]
Thank you, we are aware of this issue. At the moment it is like this because deleting the flight could be also the wrong choice if the user disconnects. Setting the flight "private" until confirmed would show some flights in your list which are not taken into account for competitions and are "invisible" to others. This could lead to confusion as well.

In the current design, the pilot has to close the window on the upload page to trigger this issue. Choosing "save" is not possible without confirming the airspaces etc. and the other button deletes the flight.

What is your suggestion?

**Comment by deltafox44** [comment]
Also, when uploading directly from the flight computer (LXnavigation for instance), flight is validated automatically without any checkbox. I think this is appropriate and that we do not want anything that would make uploading more difficult or time consuming. 

When creating the account there should be a checkbox to certify that one will only upload flights without any airspace violation, once for all. But after loading, it should be easier to select several flights to be edited together (such as correcting glider type, or deleting several flights more quickly)

**Comment by samuel-git** [comment]
General checkbox is not sufficient because airspace violations are only visible when uploading.
I think the current solution with the current tradeoffs is sufficient for now.
