### ISSUE TITLE
Bitner: Wrong task factor for FAI triangle with start point in the leg

### ISSUE THREAD

**Issue by p-bartczak** [weglide/bugtracker#193]
Example flights:

- https://www.weglide.org/flight/187868 - there is task factor fk = 0.95 instead fk=1,05
- https://www.weglide.org/flight/166617 - there is task factor fk = 0.8 instead fk=1,05

The same pilot who should get many points more ;).

**Comment by moldhouse** [comment]
I think you mixed the two flights up.

For [this flight](https://www.weglide.org/flight/166617), the task factor is 0.95 (3TP). You expect it to be 1.05 (FAI Triangle). However, the task is not a valid FAI Triangle (shortest leg must at least be 25% of the total distance.

For [this flight](https://www.weglide.org/flight/187868), the task factor is 0.8 (Free Speed). You expect it to be 1.05 (FAI Triangle). But it is not a triangle because the declared task has some weird shape (see screenshot).

<img width="1811" alt="image" src="https://user-images.githubusercontent.com/24278651/180410457-add4f27e-9473-410c-952e-b8fe4a9380e2.png">

Feel free to reopen the issue if there are any other problems.

**Comment by bdorozko** [comment]
Hi, I agree it's not an FAI triangle but definitely is a triangle in both cases. The second one has an artefact - 2nd turn point added by mistake, but lying on the second leg - as you see it is a triangle and the factor should be 1,0.
Thanks,
Bogdan
