### ISSUE TITLE
End of flight cut off

### ISSUE THREAD

**Issue by kaleu2** [weglide/bugtracker#20]
**Describe the bug**
The last 1-2 minutes before landing of some flights are cut off (neither scored nor shown on the map/baro nor available for selection when setting the scoring window). However, if you download the IGC again from weglide, it is complete including the last minutes, landing and a few seconds on the ground.
If I try to set a later end of scoring time, corresponsing to the actual landing time in the IGC file, the score is not calculated at all.

https://beta.weglide.org/flights/3384
https://beta.weglide.org/flights/3380

**Expected behavior**
The flights should be shown until the end of the IGC or at least until the end of the flight and scoring should be possible until that time as well.

**Device (please complete the following information):**
So far, for me it only happens with flights from a Nano3 logger. Flights from other loggers are scored/shown until the landing. (No influence of uploading device/browser).

**Comment by moldhouse** [comment]
Thanks for reporting. This seems to be an issue with the landing detected too early. We cut the flight track off some minutes after landing. I will have a look into it.

**Comment by moldhouse** [comment]
These are two separate issues. First one is faulty flight detection which should be fixed with the release from this afternoon. Please report if you still encounter this issue. We calculate flight probability for individual fixes based on ground speed, altitude change and height above ground and then try to find maximum likelihood decoding. We have replaced the function for mixing these probabilities by a (hopefully) better one. Second issue is an internal error when adjusting scoring times and will be fixed tomorrow. Thanks again for reporting.

**Comment by kaleu2** [comment]
It looks like landing detection works fine now and scores are also calculated after changing the scoring times. 
Thanks and keep up the great work!

**Comment by CarstenSon** [comment]
With the adjustments, the DMSt scoring is also correct for my flight referenced in #17
