### ISSUE TITLE
Custom title for flight

### ISSUE THREAD

**Issue by ArnulfKoch** [weglide/bugtracker#201]
Feature request: To improve the flight story and make it more emotional and also make it more attractive to click on flights or to know what to expect, it would be nice to be able to give the flights a title and a short description.
These should be displayed mainly on the overview pages, but of course also on the flight detail.

To keep it clean, the character lengths should be limited so that it fits into one line (title) or two lines (short description) on the most common screen resolutions.

![2022-08-06 15_40_08-Arnulf Koch](https://user-images.githubusercontent.com/42880214/183251690-dae6b349-e849-49f7-9b08-b3af22eb38a4.png)

**Comment by samuel-git** [comment]
Great idea! For this beeing consistent across flights the title would need to be mandatory which is something I am hesitant about. We have a similar view for the feed:
<img width="1009" alt="grafik" src="https://user-images.githubusercontent.com/22152728/183264351-73bf063a-6f18-4e63-859e-ce960f73b2cb.png">

Open for ideas and suggestions from everyone here :-)

**Comment by samuel-git** [comment]
I would distinct between Instagram and our approach because we have a much more defined niche (random picture vs. flight with lots of specific stats + map).
In my view this reduces the need for more refining information like a title. Another point against the title is simple but not to underestimate: Another input field which overwhelms the pilot more when uploading the first time or in a hurry. So we try to keep the information the user has/can add to a minimum.

On the plus side the title brings a lot of personalization and recognizability to a flight which is something I like.

If there are other points for/against a title I would love to broaden the discussion to a wider audience, the pinned comments can be used as a description right now and is flexible on purpose.

**Comment by moldhouse** [comment]
Do we have any example platform where this if working well? I only know Komoot and Strava where every title is something like `Small run in the afternoon`
