### ISSUE TITLE
Verein "Dithmarscher Luftsportverein" zeigt 0 Piloten/Flüge etc

### ISSUE THREAD

**Issue by malloc100** [weglide/bugtracker#206]
![grafik](https://user-images.githubusercontent.com/3018398/195625251-b11e36bb-b05e-458d-80ab-224962b291a0.png)

**Comment by samuel-git** [comment]
Hi @malloc100,
this is because the stats show only the totals from the current season.
There are no flights since 1th of October this year for this club https://www.weglide.org/flight?order_by=-scoring_date&club=Dithmarscher%2520Luftsportverein,305 :-)
I agree that we have to make this clearer.
Cheers
