### ISSUE TITLE
'File invalid' ?

### ISSUE THREAD

**Issue by deltafox44** [weglide/bugtracker#212]
**Describe the bug**
For some flights it shows "File invalid" red badge without any apparent reason; there is a the link on the badge to [Approved loggers](https://docs.weglide.org/contests/loggers.html) but without any "error code".

**To Reproduce**
1. Go to [13 august flight](https://www.weglide.org/flight/207949) for instance
![image](https://user-images.githubusercontent.com/82087770/213870544-9286e02b-a6a0-479f-8a0d-525f876f014b.png)
2. Click on 'File invalid'
No indication of what is invalid. The logger is the same on all my flights in the year, and there is a G record in the file. Is the G-record invalid ? [edit : most probably it was a logger failure - a few flights later I got an error message saying that private key was not valid] 
See [my other flights](https://www.weglide.org/flight?user=Denis%2520Flament,4019&order_by=-scoring_date&season=2022) : There are 5 invalid flights (one for claiming too late, but 4 for 'file invalid'). Invalid flights are scored normally, only the green badge in first column (#) is missing.
![image](https://user-images.githubusercontent.com/82087770/213870446-dad47174-5543-402b-b46e-4911227e4894.png)

**Expected behavior**
1.  'file invalid' or 'IGC invalid' badge if the file does not pass IGC validity check2.

If the file is invalid : 

3. there should be a link on 'file invalid' badge to the error code that explains why it is invalid and help correct for future flights. As there is when clicking on "Flight valid/invalid" - see first screenshot above.

4. There should be a 'invalid' red badge in the list of flights, first column (#) (see above), instead of just no green badge, with a link or help ballon to explain that the flight is counted in the pilot's totals but not for his rankings since it is invalid

5. There should be a box with 'Invalid' / 'invalid file' as in this screenshot from this [25 july flight](https://www.weglide.org/flight/197026):
![image](https://user-images.githubusercontent.com/82087770/213870355-e63a4ead-1f1f-4650-9c1e-1d5ab3b87770.png)

Also, when the flight is valid, but contains ['information' or 'warning' codes,](https://docs.weglide.org/contests/errors.html) like in this other [flight](https://www.weglide.org/flight/192665):

6. there should be an orange 'flight valid' badge, not a green one ; because you cannot know there have been warnings if you don't click on the badge - as in this screenshot:
![image](https://user-images.githubusercontent.com/82087770/213872096-8b290591-8d7e-4298-b12b-60586c91dae6.png)

**Comment by flyingjoe** [comment]
Hi @deltafox44, 

thanks for bringing that up. 

# Your file
I manually checked your invalid files, and they really do seem to be invalid (it's mostly a black box for us aswell): 

<img width="269" alt="image_2023-01-26_09-48-24" src="https://user-images.githubusercontent.com/28477393/214801829-f0cc6394-6256-4f76-a1e1-849bc0abb05f.png">

You may want to reach out to your logger manufacturer about this.

# Docs
I think you are correct, there were no clear explanations on what "file invalid" may mean. I added explanations to the [doc](https://docs.weglide.org/contests/loggers.html) see ([what can I do?](https://docs.weglide.org/contests/loggers.html#my-files-show-up-as-invalid-what-can-i-do) and [checking myself](https://docs.weglide.org/contests/loggers.html#my-files-show-up-as-invalid-what-can-i-do)).

I don't really think it makes sense to expand the "File invalid" badge, since we don't know why it is invalid. I think the improved docs should help with this.  

# Better indication

As it currently stands, there are three validations to pass to be scored for a contest: 
1. "Flight valid": Formal requirements to flight trace need to be passed ([Scoring Error Codes](https://docs.weglide.org/contests/errors.html)
2. "IGC valid": G-Record validation of IGC-File needs to pass
3. Formal requirements of certain contest need to be passed (e.g. uploaded to late -> can vary between contests for a single flight)

We are working on improving the error messages, but it's not that easy as every abstraction can bring in more complexity.
E.g.: Let's assume we were to do a single "Flight valid" badge, combining all of them:
1. Green -> Okay great
4. Orange -> Click on it -> expand to flight valid and igc-valid -> flight valid is orange -> Click on it -> some contests are valid and some are not, due to different upload date requirements

About the list indicator: 
We actually experimented with the red indicators in the list before releasing the "new" list but decided against it, as it became quite irritating in some cases.

**Comment by deltafox44** [comment]
Hi @flyingjoe

Thank you for your answer. Clicking on 'file invalid' badge now redirects to the explanations you added and it's ok. So 'file invalid' means that integrity check (G-Record) failed. I will see with LXNavigation about that. 

About the list indicator:
It is not obvious at first glance of the list of flights that a green indicator means 'valid flight', thus a flight without green indicator is invalid. It would be clearer if, for instance, there was 'Valid' instead of '#' as first column header.

Still, some indication that there has been 'information' or 'warning' codes would be useful not to miss the warnings (cf my item # 5 above)

**Comment by moldhouse** [comment]
I agree regarding item 5. Currently, you miss the warnings and they can be useful (e.g. if you have many invalid fixes you know that you should reposition your logger. Maybe show it in yellow? However, a potential downside is that it indicates that something is wrong although your flight is valid. @samuel-git do you have an opinion?

**Comment by samuel-git** [comment]
In my opinion we should use green if no action is required from the user.
I would leave it as is, but maybe indicate if there are warnings with an icon or similar.

**Comment by samuel-git** [comment]
<img width="416" alt="grafik" src="https://user-images.githubusercontent.com/22152728/219212790-b372641d-d7da-4628-81e4-59c30838f63b.png">
Like this (also for valid flights)?

**Comment by deltafox44** [comment]
> As it currently stands, there are three validations to pass to be scored for a contest:
> 
> 1. "Flight valid": Formal requirements to flight trace need to be passed ([Scoring Error Codes](https://docs.weglide.org/contests/errors.html)
> 2. "IGC valid": G-Record validation of IGC-File needs to pass
> 3. Formal requirements of certain contest need to be passed (e.g. uploaded to late -> can vary between contests for a single flight)

![image](https://user-images.githubusercontent.com/82087770/219400643-1b246068-108d-4bc2-a265-36fc028fe412.jpeg)
The second button is quite straightforward since it is only related to file integrity - Green "IGC valid"  or red "IGC invalid"  with a link to [help](https://docs.weglide.org/contests/loggers.html) -> nothing to change here (except perhaps "IGC invalid" instead of "File invalid")

But in my opinion the first button should provide a better indication: 
- green "Flight valid", meaning everything is OK for scoring and analysis -> click on it -> expand to "No remarks analysing this flight", or 
- yellow "Flight warnings", meaning valid at least for some contests, but with warnings or info codes -> click on it -> expand to list of [scoring errors](https://docs.weglide.org/contests/errors.html) and/or list of contest requirement failed - such as "claiming too late for DMSt", or 
- red "Flight invalid", meaning "Cannot be scored" -> click on it -> expand to show analysis or file errors 

In some cases, at present, there is a green button "Flight Valid", and a score is indicated, although the flight is NOT scored in the contest rankings nor counted in the list totals. This is very confusing. Only the absence of a green number button in the list of flights indicates the flight is not really scored (as shown in my first post above). There should NOT be a green button but a red (or yellow).

See for instance : 

- [flight 64063](https://www.weglide.org/flight/64063), where IGC file is invalid, but flight otherwise valid 
![image](https://user-images.githubusercontent.com/82087770/219417847-786a16a4-39ec-45f1-9f4a-8b0b4a01e140.jpeg)
![image](https://user-images.githubusercontent.com/82087770/219420548-8a1477d9-7c59-476e-be3e-9b62fc342991.jpeg)
There should be a red button "Flight invalid" -> click on it -> expand to show  "IGC invalid, will not be scored" 

- [flight 74569](https://www.weglide.org/flight/74569), where the flight analysis is valid, but it cannot be scored due to claiming too late
![image](https://user-images.githubusercontent.com/82087770/219429213-34cab4b2-091f-405a-bed2-021b6a79404b.jpeg)
![image](https://user-images.githubusercontent.com/82087770/219429859-b6c1bdab-ee98-4745-8569-e7496b1ba508.jpeg)
There should be a red button "Flight invalid" -> click on it -> "Claimed too late for all contests" - or a yellow button "Flight warnings" -> click on it -> "Claimed too late for some contests"

**Comment by deltafox44** [comment]
Update : it seems OK now 👍 

There have been a significant improvement, it's now much clearer since Status are indicated by red/yellow/green dots and clicking on them give explanations - see for instance the same two flight as above :
[flight 64063](https://www.weglide.org/flight/64063) :
![image](https://github.com/weglide/bugtracker/assets/82087770/7dc8d09c-4576-48c5-953a-80a7c7c588f4)

and [flight 74569](https://www.weglide.org/flight/74569) :
![image](https://github.com/weglide/bugtracker/assets/82087770/40d75118-122e-45c5-9611-6639102efb5b)
