### ISSUE TITLE
Bring It Home badge is wrongly awarded.

### ISSUE THREAD

**Issue by vacaretutudor** [weglide/bugtracker#265]
**Describe the bug** 
On flight https://www.weglide.org/flight/352983 the Bring It Home badge is awarded even though there is no final glide of at least 50km. 

**To Verify the issue Steps to reproduce the behavior:**
1. Go to https://www.weglide.org/flight/352983
2. Scroll down to "Badges"
3. See Awarded Badge(s). (Verify that Bring It Home badge is awarded)
4. Look at the flight and verify final glide.

**Expected behavior** 
Bring It Home Badge should be awarded only to flights that have at least 50km final glide.

**Screenshots**
See attached.
<img width="1360" alt="Screenshot 2023-12-19 at 13 47 31" src="https://github.com/weglide/bugtracker/assets/6464247/e1648336-ff41-48bf-8613-846087a4ad5e">

**Device** (please complete the following information):
* Device is not relevant in reproducing the bug.

**Comment by moldhouse** [comment]
Thank you for taking the time to report. I think the issue is the definition of a "final glide". We take the final (last) glide: the glide after the last thermal (which can also be around a turnpoint). I agree that this can be confusing for wave or ridge flights, but I think sticking with the exact wording is the best we can do at the moment.

Again, we appreciate you taking the time of raising the issue.

**Comment by vacaretutudor** [comment]
@moldhouse - I think the definition of 'final glide' is not correct. Any deviation on course for the final glide which is bigger than 90 degrees could be considered as a turn (or turnpoint). This way WeGlide would avoid awarding the badge for ridge flights that sum up the distance in more legs.
