### ISSUE TITLE
Incorrect 'Missed Turnpoint 1' error on task declaration

### ISSUE THREAD

**Issue by apm2000g** [weglide/bugtracker#274]
For this flight [https://www.weglide.org/flight/370866](https://www.weglide.org/flight/370866) the task reports as 'Missed Turnpoint 1', but it appears to be clearly rounded. XCSoar recorded the turnpoint met in flight and also the task completed. Any reason why WeGlide thinks this was not flown correctly?

![image](https://github.com/weglide/bugtracker/assets/165639981/cd0e9a30-2099-48b9-b1a8-1b2fb0317a12)

**Comment by deltafox44** [comment]
@apm2000g 'Keyhole' tasks have a start line (a beer can only at finish), and the start line was missed (crossed only in tow, as shown below). 

This is a good reason why the task was not 'rounded', though the report should be 'No start' instead of 'Missed Turnpoint 1'
![image](https://github.com/weglide/bugtracker/assets/82087770/45c1edb5-d4a4-43a3-9a6a-88bb6e08c7cc)

**Comment by deltafox44** [comment]
Sorry I did not notice the start just before landing ;-)

The error message is not misleading, but when it is not obvious
 it may be difficult to find why the reason why it was missed. 

It would be good to develop the error message giving clues to what was completed or missed. In this case something like "Start à 08:16 at 456 m MSL" & "Last fix at 08:17 at 30 km of TP1" would help understanding. In any other miss cases (TP sector missed by a few meters, more than 1000 m difference between start and finish, etc.) It would help too...

It could be added to "Statistics/Task" tab. As said on another thread these statistics should be present for each leg even when the task was not completed.  Clicking on the error message "Missed TP1" could link to these statistics, rather than at present to "Why do I get no extra points for my declaration?".
