### ISSUE TITLE
Improve/fix ENL coloring in barogram

### ISSUE THREAD

**Issue by niggli** [weglide/bugtracker#56]
**Describe the bug**
When I upload a flight and the type of glider is a motorglider from the beginning, the time during engine run is yellow in the barogram. If I edit a flight because the type of glider was entered as a pure glider, and then change it to a motorglider, the ENL is not shown.

**To Reproduce**
1. Upload flight with engine run
2. Select "ASG 29 18m" as glider type and save
3. Edit this flight and change type to "ASG29 E 18m"

**Expected behavior**
The barogram should always be yellow during engine run. Additionally, for the selection of the correct "Wertungsfenster" it would really help to be able to already see a small map view, especially if the flight has multiple engine runs.

**Screenshots**
<img width="1261" alt="Bildschirmfoto 2021-01-03 um 23 16 44" src="https://user-images.githubusercontent.com/529670/103490119-f36ba880-4e19-11eb-8f5f-891fd77a41c2.png">

**Device (please complete the following information):**
 - Device: MacBook Pro
 - OS: OS X Catalina
 - Browser: Safari

**Comment by samuel-git** [comment]
#57 is related.

Proposal: make ENL switchable with a second tab like airspaces.
What do you think?

**Comment by Dimowelle** [comment]
ENL should not be switchable and should always for everybody be visible, because there are too many Guys cheating and I want direct to see possible missbehaviour ... 
I am very sad about that sportsmen - not only for competition, but simply for easy comparison. Everybody have to control their gliding window. 

By default I appreciate a Low noise level, so the gliding windows gets smaller and the pilot have to choose and edit the window. For komfort the glide start and end time should be clickable in the window-area, maybe with a sliding function. 
I ever have to adjust the correct start and end time, so a low noise level is no problem.

**Comment by niggli** [comment]
I agree, it should always be visible or at least per default visible.

**Comment by samuel-git** [comment]
@Dimowelle @niggli it's online but off on default. This decision is not final but I think especially on mobile the baro becomes too cluttered with 3 different time-series. Also the axes become unclear.

For scoring window adjustment in the barogram directly, we had it this way first but decided against it because of mobile/small devices. It's just not possible to zoom, zoom the barogram drag the barogram and drag the scoring window on smaller touch screens.
I'm open to better ideas, as I agree that thats not the friendliest UX way.

**Comment by niggli** [comment]
Thanks, works for me!

If I really have to check and adjust my scoring window, in the last years I always had to open the flight in another tool which had a map for, example SeeYou. I then wrote the exact timestamp on a piece of paper and edited it in OLC. Having just the barogram, it's often not possible to be sure if the algorithm has found the correct moment of tow release. So ideally I would be able to look at a very zoomed in map of the scoring window boundaries directly in weglide when claiming/editing a flight. But of course that would also be a bit of an overload for mobile devices.

Coloring the flight track in another color during engine use could also be a good idea, like LXNAV does in their flight computers.

**Comment by Dimowelle** [comment]
Thank you, works also for me :-)

Only coloring the flight-track is not so good, because the amount of noise-level gets lost. The implemented way now is the better way - for me.

A simple idea for easy adjustment of the scoring window - using both methods:
manually edit in the fields Start/End 
OR click in Start and then Click in the window, so that the time from the window appears in the Start-field. (analog for End-time).
This is a similar way as booking in booking.com.

Congratulation for the very good implementation of multiple choices for gliding windows:
 - Often it happens that there are more possible gliding windows
 - Pilots have to decide which window they choose
 - Therefore a low noise-level is ok
.... it is much better than olc, where only one window is automatically offered on a high noise-level, so that there are many flights with too long gliding windows without necessary manual adjustment.

Thank you!

**Comment by samuel-git** [comment]
Will close this issue and come back when we have a good idea for the scoring edit. Thanks for the input and discussion!
