### ISSUE TITLE
Airspace positioning and altitude calculation issues

### ISSUE THREAD

**Issue by Scumi** [weglide/bugtracker#68]
**Describe the bug**
a) Airspace position does not align between barogram and map.
b) Airspace altitude is not correctly displayed and also taken incorrectly for airspace violation.

A violation was shown in the flight upload form and can be seen in the barogram, but not on the same position on the map.
It also appears to me, that the airspace is always provided in feet (also shown on the map) despite my personal setting being metric. I guess that leads to the altitude violation.

**To Reproduce**
1. Go to https://beta.weglide.org/flights/9336
2. Review flight path, altitude and airspace on map and baro at 
- 12:26:18 (lower airspace boundary should be 1981m instead of feet)
- 12:42:00 

**Expected behavior**
a) Consistent airspaces in barogram and map view.
b) Correct calculation and display of airspace altitudes.

**Screenshots**
![airspace_violation_weglide](https://user-images.githubusercontent.com/26870072/104121012-88e7ca80-533b-11eb-8087-03d530ec9b39.png)

**Device (please complete the following information):**
 - Device: PC
 - OS: Linux
 - Browser: Firefox

**Comment by frantzheld** [comment]
I have the guess, that the map displays the old airspace (before 09.11.2020), while in the barogram the new one (after opening BER airport) is used.

I have the same issure at this flight: https://beta.weglide.org/flights/844

With the old airspace there should be no violation:
<img width="596" alt="berlin" src="https://user-images.githubusercontent.com/47079209/104124922-db34e580-5353-11eb-92f5-41914315ccca.png">

Same flight section with seeyou and the new airspace:
<img width="461" alt="su" src="https://user-images.githubusercontent.com/47079209/104125064-b2612000-5354-11eb-85ab-ea88d3309a01.png">

**Comment by frantzheld** [comment]
The label "Berlin C 1981.2ft/3048ft", which should be "Berlin C 1981m/3048m" seems to be another independent issue.

**Comment by samuel-git** [comment]
@moldhouse we should unify airspace-tile altitude units and update them too.

**Comment by tisoen** [comment]
I've just spotted something else that might be related:

**Describe the bug**
Airspace altitudes seem to be AGL in the barogram where they should be AMSL.
(Also the values are in m and the units in ft as described by Scumi)

**To Reproduce**
- View a flight close to an airspace
- Look at the airspace indication in the barogram and notice it doesn't match the MSL altitude on the map

**Expected behavior**
Consistent airspaces in barogram and map view regarding altitude, maybe due to a AGL/AMSL error.

**Screenshots**
![image](https://user-images.githubusercontent.com/13700539/105614469-f11dbe00-5dc9-11eb-9227-effc0a3eb7aa.png)
Notice the airspace upper border is slightly above 2000 m AMSL instead of slightly below (Terrain height is around 120 m at this location)

**Device (please complete the following information):**
Device: PC
OS: Windows 10
Browser: Google Chrome 87

**Comment by moldhouse** [comment]
We adjust airspace altitude provided in FL based on QNH of the flight. I suspect this to be the reason for this shift.

**Comment by moldhouse** [comment]
We have deployed the new airspace tiles. If you empty your cache, the airspace on the map and the provided altitude should now be correct.
